spring:
  application:
    name: desafio
  datasource:
    url: jdbc:h2:mem:h2db
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
      format_sql: true
      type: trace
      use_sql_comments: true
    defer-datasource-initialization: true
server:
  port: 8080

jwt:
  secret: secretkey123